name: Pull Request Continuous Integration
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Load Cached Venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Linter
        run: poetry run flake8

      - name: Jira
        id: jira
        run: echo "::set-output name=issue::$(poetry run jira-issue-script 10004 ${{ secrets.FLC_JIRA_TOKEN }})"

      - name: echo_task
        id: echo_jira
        run: echo "${{ steps.jira.outputs.issue }}"

      - name: Echo Branch
      - uses: bvkimball/branch-vars@1.0.1

      - run: echo ${CURRENT_BRANCH}

      # - name: Git Current Branch
      #   id: current_branch
      #   run: echo "::set-output name=branch::${{ git branch --show-current }}"

      # - name: echo_branch
      #   id: echo_jira
      #   run: echo "${{ steps.current_branch.outputs.branch }}"
